# Generated by Django 6.0.7 on 2026-07-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkcollection',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='milkcollection',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
